package com.micabytes.util

enum class Group {
  LEADER,
  SECOND,
  PATHFINDER,
  MAINTAINER,
  HEALER,
  ATTENDANT,
  MEMBER;
}

enum class TraitType {
  NONE,
  BELIEF,
  PERSONALITY,
  TITLE,
  HEALTH,
  INJURY,
  OPINION,
  TIMESTAMP,
  RESPONSIBILITY,
  PREDILECTION,
  PERSON_EVENT,
  MIL_RANK,
  ARMY_RANK,
  CIVIL_RANK,
  EXPERIENCE,
  SHIP,
  BIRTH,
  LOCATION,
  FACTION,
  LOCATION_GOVERNOR,
  LOCATION_RUMOR,
  GROUP_LEADER,
  GROUP_SECOND,
  GROUP_PATHFINDER,
  GROUP_MAINTAINER,
  GROUP_HEALER,
  GROUP_ATTENDANT,
  GROUP_MEMBER;

  fun isGroup() = when (this) {
    GROUP_LEADER, GROUP_SECOND, GROUP_PATHFINDER, GROUP_MAINTAINER, GROUP_HEALER, GROUP_ATTENDANT, GROUP_MEMBER -> true
    else -> false
  }

}